name: p2mpy
channels:
    - https://conda.anaconda.org/menpo
dependencies:
    - python
    - numpy
    - scipy
    - numba
    - h5py
    - matplotlib
    - scikit-learn
    - opencv
    - pip:
        - Cython
        - scikit-image
        - plyfile
        - MeshPy
