name: p2mpy
channels:
    - https://conda.anaconda.org/dougal
dependencies:
    - python
    - numpy
    - scipy
    - numba
    - h5py
    - matplotlib
    - scikit-learn
    - opencv
    - flann=1.9.1
    - pip:
        - Cython
        - scikit-image
        - plyfile
        - pyflann
        - pycollada
